### PR TITLE
Make /etc/issue logo more pretty and include the name "DebOps"

### PR DESCRIPTION
**Pull request by ypid**
I always thought the name DebOps should appear there somewhere :wink: 

Before:

before

After:

after

### CODE REVIEW

**Comment by drybjed** [comment]
Hmm, I dunno... It's not symmetric, looks inda weird... Any other ideas?

**Comment by ypid** [comment]
screenshot from 2016-08-01 21 51 04

**Comment by ypid** [comment]
Updated:
screenshot from 2016-08-01 22 58 11

I guess the real logo (currently under constriction) will be subject to change.

**Comment by ypid** [comment]
screenshot_owncloud template_2016-08-01_23 01 39

**Pull request merged**
