### PR TITLE
fix proc_hidepid of lxc

### PR DESCRIPTION
**Pull request by le9i0nx**

### CODE REVIEW

**Comment by le9i0nx** [comment]
sorry.
in lxc can not edit / etc / fstab
and attempt to remount the / pros fails

**Comment by drybjed** [comment]
Oh, I know what's up. @le9i0nx, do you have `cap_sys_admin` enabled in your LXC containers? This should allow configuration of `/proc`. If not, do you have `debops.core` enabled on that host? It created a fact script that checks what POSIX capabilities are available. The `debops.console` role [checks these facts already](https://github.com/debops/ansible-console/blob/master/tasks/main.yml#L107-L109) and doesn't configure `/proc` if `cap_sys_admin` is not available, like in LXC containers created by default by DebOps using `lxc-debops` script.

This of course could be moved to the default variable instead of being put statically with the task. Well, the wole role needs a revamp, anyway. It will be done with time. :-)

**Comment by le9i0nx** [comment]
strange.
I canceled your changes and restart the role but the error did not happen.
here error
``` yaml
TASK [debops.console : Configure /etc/motd] ************************************
changed: [cups.ufa.mpautina.ru]
--- before
+++ after: dynamically generated
@@ -0,0 +1,3 @@
+-------------------------------------------------
+        This system is managed by Ansible
+-------------------------------------------------


TASK [debops.console : Configure fsck behaviour on boot] ***********************
changed: [cups.ufa.mpautina.ru]
--- before: /etc/default/rcS (content)
+++ after: /etc/default/rcS (content)
@@ -21,5 +21,5 @@
 #VERBOSE=no
 
 # automatically repair filesystems with inconsistencies during boot
-#FSCKFIX=no
+FSCKFIX=yes
 HWCLOCKACCESS=no


TASK [debops.console : Ensure that specified locales exist] ********************
changed: [cups.ufa.mpautina.ru] => (item=en_US.UTF-8)

TASK [debops.console : Set default system locale] ******************************
changed: [cups.ufa.mpautina.ru]

TASK [debops.console : Update /etc/default/locale] *****************************
changed: [cups.ufa.mpautina.ru]

TASK [debops.console : Get list of available text editors] *********************
ok: [cups.ufa.mpautina.ru]

TASK [debops.console : Configure system-wide editor] ***************************
ok: [cups.ufa.mpautina.ru]

fatal: [cups.ufa.mpautina.ru]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /proc: mount: cannot remount proc read-write, is write-protected\n"}


```

**Comment by drybjed** [comment]
@le9i0nx In the LXC container on `root` account, run command:
```
capsh --print | grep cap_sys_admin
```
If you get anything, it means that `cap_sys_admin` is present. But the host might still protect `/proc` from being modified from inside of the container.

I wonder if you have `cap_sys_admin` enabled; alternatively, how did you create that LXC container - was it with the template provided by the `debops.lxc` role or some other source, like a VPS provider?

**Comment by le9i0nx** [comment]
```
Current: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_syslog,cap_wake_alarm,cap_block_suspend,37+ep
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_syslog,cap_wake_alarm,cap_block_suspend,37
```
I used api proxmox

**Comment by drybjed** [comment]
Yup, you have `cap_sys_admin`. So I guess that Proxmox gives that to the host and secures `/proc` some other way.

OK then, what to do about this... I'm not really sure how to detect this situation without trying to remount `/proc` in the first place. Limiting `hidepid` to host that are not LXC containers feels clumsy to me, since there might be some configurations where you can remount `/proc` just fine.

My original idea was that if you encountered such problem, you could create a separate `[lxc_no_proc]` Ansible group or something like that, put all LXC containers there and set `console_proc_hidepid: False`, that would take care of this issue on the inventory level. Do you think that would work for you?

**Comment by le9i0nx** [comment]
Thank you.
I've done but it's cumbersome decision
I think I move to a common group the option proposed in the patch.

**Pull request closed without merging**
